# Site settings
title: Dani Solomon
# tagline: "Hey look at this cool website"
url: "http://danibsolomon.com"

# Pages
# This is where you link to each page in your header

permalink: /:collection/:name/

navpages:
  "About Me": "about"
  "Games": "games"
  "Illustration": "illustration"
  "Voice Acting": "voiceacting"

# Social
socialimg: /img/hbkj_snapper_v2.png

collections:
  games:
    output: true
    permalink: /:collection/:title/
    name: Games
    url: /games/
  illustration:
    output: true
    permalink: /:collection/:title/
    name: Illustration
    url: /illustration/

defaults:
  - scope:
      path: ""
      type: games
    values:
      layout: project
  - scope:
      path: ""
      type: illustration
    values:
      layout: gallery

# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
